name: Browser tests

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    workflow-experience:
        name: "Notifications browser tests - Experience"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: 'experience'
            test-suite:  '--profile=workflow --suite=workflow-full'
            test-setup-phase-1: '--profile=setup --suite=workflow --tags=@part1 --mode=standard'
            test-setup-phase-2: '--profile=setup --suite=workflow --tags=@part2 --mode=standard'
            setup: "doc/docker/base-dev.yml:doc/docker/db-postgresql.yml:doc/docker/selenium.yml"
        secrets: inherit